export const PERMISSIONS = {
  STAFF_VIEW: "staff.view",
  STAFF_CREATE: "staff.create",
  STAFF_UPDATE: "staff.update",
  STAFF_DELETE: "staff.delete",

  PROGRAM_VIEW: "program.view",
  PROGRAM_CREATE: "program.create",
  PROGRAM_UPDATE: "program.update",
  PROGRAM_DELETE: "program.delete",
  PROGRAM_UPDATE_STATUS: "program.updateStatus",
  PROGRAM_UPDATE_POINT: "program.updatePoint",
  PROGRAM_OVERRIDE_COMPLETED: "program.overrideCompleted",

  CORRECTION_VIEW: "correction.view",
  CORRECTION_CREATE: "correction.create",
  CORRECTION_UPDATE: "correction.update",
  CORRECTION_DELETE: "correction.delete",
  CORRECTION_UPDATE_STATUS: "correction.updateStatus",
  CORRECTION_OVERRIDE_COMPLETED: "correction.overrideCompleted",

  UPGRADE_VIEW: "upgrade.view",
  UPGRADE_CREATE: "upgrade.create",
  UPGRADE_UPDATE: "upgrade.update",
  UPGRADE_DELETE: "upgrade.delete",
  UPGRADE_UPDATE_STATUS: "upgrade.updateStatus",
  UPGRADE_OVERRIDE_COMPLETED: "upgrade.overrideCompleted",

  DESIGN_VIEW: "design.view",
  DESIGN_CREATE: "design.create",
  DESIGN_UPDATE: "design.update",
  DESIGN_DELETE: "design.delete",
  DESIGN_UPDATE_STATUS: "design.updateStatus",
  DESIGN_UPDATE_POINT: "design.updatePoint",
  DESIGN_OVERRIDE_COMPLETED: "design.overrideCompleted",

  SOURCE_VIEW: "source.view",
  SOURCE_CREATE: "source.create",
  SOURCE_UPDATE: "source.update",
  SOURCE_DELETE: "source.delete",
  SOURCE_SEND_MAIL: "source.sendMail",
  SOURCE_UPDATE_STATUS: "source.updateStatus",

  WEBSITE_TEMPLATE_VIEW: "websiteTemplate.view",
  WEBSITE_TEMPLATE_CREATE: "websiteTemplate.create",
  WEBSITE_TEMPLATE_UPDATE: "websiteTemplate.update",
  WEBSITE_TEMPLATE_DELETE: "websiteTemplate.delete",

  SERVER_VIEW: "server.view",
  SERVER_CREATE: "server.create",
  SERVER_UPDATE: "server.update",
  SERVER_DELETE: "server.delete",

  CONTRACT_VIEW: "contract.view",
  CONTRACT_CREATE: "contract.create",
  CONTRACT_UPDATE: "contract.update",
  CONTRACT_DELETE: "contract.delete",
  CONTRACT_SEND_MAIL: "contract.sendMail",
  CONTRACT_OVERRIDE_HANDOVER: "contract.overrideHandover",

  PRICE_VIEW: "price.view",
  PRICE_CREATE: "price.create",
  PRICE_UPDATE: "price.update",
  PRICE_DELETE: "price.delete",

  CONFIG_CATEGORY_VIEW: "config.category.view",
  CONFIG_CATEGORY_UPDATE: "config.category.update",
  CONFIG_MAIL_VIEW: "config.mail.view",
  CONFIG_MAIL_UPDATE: "config.mail.update",
  CONFIG_SETTING_VIEW: "config.setting.view",
  CONFIG_SETTING_UPDATE: "config.setting.update",

  TEMPLATE_VIEW: "template.view",
  TEMPLATE_CREATE: "template.create",
  TEMPLATE_UPDATE: "template.update",
  TEMPLATE_DELETE: "template.delete",
  TEMPLATE_SET_DEFAULT: "template.setDefault",

  PERMISSION_USER_VIEW: "permission.user.view",
  PERMISSION_USER_CREATE: "permission.user.create",
  PERMISSION_USER_UPDATE: "permission.user.update",
  PERMISSION_USER_DELETE: "permission.user.delete",
  PERMISSION_ROLE_VIEW: "permission.role.view",
  PERMISSION_ROLE_UPDATE: "permission.role.update",
};
